site_name: Efficient Paper

nav:
  - Home: index.md
  # - Paper List:
  #   - By Year: cls_year.md
  #   - By Keyword: cls_keyword.md
  #   - By Publication: cls_publication.md
  #   - By Institution: cls_institution.md
  #   - By Author: cls_author.md
  # - Full List: readme.md
  - Graph: baseline_methods_graph.md
  - Weekly Paper: weekly_paper/
  - Contributors: contributors.md
theme:
  name: readthedocs
  custom_dir: overrides

markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - toc
  - mdx_math:
      enable_dollar_delimiter: True #for use of inline $..$

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/prism.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/components/prism-clike.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/components/prism-python.min.js
  - js/prism-prototxt.js
  - js/preview.js
  - js/back-to-top.js
  - js/note-editor.js


extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/themes/prism.css
  - css/extra.css

plugins:
  - glightbox
  - literate-nav
  - macros
  - mermaid2
  # - search

  # - git-latest-changes:
  #     limit_to_docs_dir: True       # 仅限 docs 目录
  #     history_limit: 9              # 最近 3 条记录
  #     timestamp_format: "%Y-%m-%d %H:%M"
  #     table_features:
  #       - "page_path_link"
  #       - "timestamp"
  #       - "author"
  #       - "message"